/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Open Command Boards in an area of the shell, or as a popup (requires accepting pop-ups)
 */
export type LaunchArea = 'main' | 'left' | 'right' | 'popup';

/**
 * Lightweight Command Boards
 */
export interface CommandBoards {
  launch_area?: LaunchArea;
  boards?: DefinedBoards;
  [k: string]: unknown;
}
/**
 * create Command Boards
 */
export interface DefinedBoards {
  [k: string]: CommandBoard;
}
/**
 * new boards
 */
export interface CommandBoard {
  /**
   * The human-readable to show in Command Board launchers
   */
  title: string;
  /**
   * Relative position of the board in its Category
   */
  rank?: number;
  /**
   * The category of Launcher items and Command Palette entries
   */
  category?: string;
  /**
   * The description of a board, show in tool tips, etc.
   */
  description?: string;
  /**
   * An SVG string for a command board
   */
  icon?: string;
  /**
   * The content of the board, as rendered by nunjucks with a variable call 'app' describing the current application
   */
  template: string;
  [k: string]: unknown;
}
