channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.11,<3.12
  ### environment-base.yml ###
  - argcomplete
  - doit-with-toml
  - jupyterlab >=3.5.2,<4
  - pip
  - python >=3.8,<3.12
  - traitlets >=5.8
  ### environment-base.yml ###
  ### environment-build.yml ###
  # runtimes
  - nodejs >=16,!=17.*,<19
  # build
  - jsonschema-gentypes
  - flit >=3.7.1
  - twine
  ### environment-build.yml ###
  ### environment-lint.yml ###
  # formatters
  - black
  - docformatter
  - isort
  - pydocstyle
  - pyproject-fmt
  - robotframework-tidy >=3.3
  - ssort
  # linters
  - robotframework-robocop >=2.6
  - pyflakes
  - mypy
  ### environment-lint.yml ###
  ### environment-docs.yml ###
  # docs
  - docutils >=0.18
  - myst-nb
  - pydata-sphinx-theme
  - sphinx >=5.1,<6
  - sphinx-autobuild
  - sphinx-copybutton
  - sphinx-jsonschema
  # check
  - hunspell
  - hunspell-en
  - pytest-check-links
  # lite cruft
  - pkginfo
  - python-libarchive-c
  - pip:
      - jupyterlite ==0.1.0b17
  ### environment-docs.yml ###
  ### environment-test.yml ###
  # test
  - coverage
  - hypothesis
  - pytest-asyncio
  - pytest-console-scripts
  - pytest-html
  ### environment-test.yml ###
  ### environment-robot.yml ###
  - robotframework >=6
  - robotframework-pabot
  # browser
  - firefox
  - geckodriver
  - robotframework-jupyterlibrary >=0.4.1
  - lxml
  ### environment-robot.yml ###
