channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.11,<3.12
  ### environment-base.yml ###
  - argcomplete
  - doit-with-toml
  - jupyterlab >=3.5.2,<4
  - jupyter_server >=1,<2
  - pip
  - python >=3.8,<3.12
  - traitlets >=5.8
  ### environment-base.yml ###
  ### environment-build.yml ###
  # runtimes
  - nodejs >=16,!=17.*,<19
  # build
  - jsonschema-gentypes
  - flit >=3.7.1
  - twine
  ### environment-build.yml ###
