channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.10,<3.11
  ### environment-base.yml ###
  - argcomplete
  - doit-with-toml
  - jupyterlab >=3.5.2,<4
  - pip
  - python >=3.8,<3.12
  - traitlets >=5.8
  ### environment-base.yml ###
  ### environment-build.yml ###
  # runtimes
  - nodejs >=16,!=17.*,<19
  # build
  - jsonschema-gentypes
  - flit >=3.7.1
  - twine
  ### environment-build.yml ###
  ### environment-lint.yml ###
  # formatters
  - black
  - docformatter
  - isort
  - pydocstyle
  - pyproject-fmt
  - robotframework-tidy >=3.3
  - ssort
  # linters
  - robotframework-robocop >=2.6
  - pyflakes
  - mypy
  ### environment-lint.yml ###
  ### environment-robot.yml ###
  - robotframework >=6
  - robotframework-pabot
  # browser
  - firefox
  - geckodriver
  - robotframework-jupyterlibrary >=0.4.1
  - lxml
  ### environment-robot.yml ###
